### ISSUE TITLE
Etch a sketch rgbShader function walktrhu

### ISSUE THREAD

**Issue by lghiggino** [kjell-fjeldsaunet/top-etch-a-sketch#1]
Dear Kjell, hello! I started following you after this project. Yours is one of the clearest of the students solution. That said, I just cannot understand HOW your RgbShader works. Would you mind walking me thtu it?

Thank you very much!

**Comment by kjell-fjeldsaunet** [comment]
Dear Leonardo,

I'm sorry, I didn't see this issue. I'm new to GitHub, so I only saw this now as you closed it.
If it is not to late, I can give a quick walk through.

The two arguments are percentage and color. If you want to darken the color, p is a number between 1 and 0. To lighten the color, it is a number above 1. Color is an rgb color code. 
The constant colors is an array made by the three numbers in the rgb code. Ex: rgb(24, 56, 87) returns [24, 56, 87]. The regex used matches any numbers with 1 to 3 digits.
Then the function returns a new rgb code where each number is multiplied by the percentage.

Please let me know if anything is still unclear.

Sincerely,

Kjell

**Comment by lghiggino** [comment]
Dear Kjell, I'm also new here. I don't even know if this here is appropriate, but nevertheless, there was too much curiosity...

My main doubt was in this line:  const colors = color.match(/[0-9]{1,3}/g);
I skipped regex up to this point, it never came up while I was solving my exercises. That code matches the array with the current color from the variable currentBackgroundColor, right?

I would like to thank you for taking the time to answer this. I appreciate it a lot.
